//    Copyright 2016 United States Government as represented by the
//    Administrator of the National Aeronautics and Space Administration.
//    All Rights Reserved.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.




// THIS IS AUTO GENERATED BY EnumCreate.cs
// DO NOT EDIT, CHANGES MAY BE OVERRIDDEN
using System;
using FirstUtilities;

namespace NamedMessageValuesExtention
{
    public enum MessageEnum { 
        AutonEnabled,
        AutonDelay,
        VisionRange,
        VisionAzimuth,
        VisionRecognized,
        DrvGyroAct,

    }

    public static class NamedValuePublisherExt
    {
        public static void Subscribe(this ValuePublisher self, MessageEnum value, Action<ValueItem> onValueUpdate)
        {
            self.Subscribe((int)value, onValueUpdate);
        }
        public static void Unsubscribe(this ValuePublisher self, MessageEnum value, Action<ValueItem> onValueUpdate)
        {
            self.Unsubscribe((int)value, onValueUpdate);
        }
    }
}