/* 
 Licensed under the Apache License, Version 2.0

 http://www.apache.org/licenses/LICENSE-2.0

 Generated by: http://xmltocsharp.azurewebsites.net/
 */
using System;
using System.Xml.Serialization;
using System.Collections.Generic;
namespace Xml2CSharp
{
    [XmlRoot(ElementName = "table_host")]
    public class Table_host
    {
        [XmlAttribute(AttributeName = "value")]
        public string Value { get; set; }
    }

    [XmlRoot(ElementName = "comm_mode")]
    public class Comm_mode
    {
        [XmlAttribute(AttributeName = "value")]
        public string Value { get; set; }
    }

    [XmlRoot(ElementName = "dest_host")]
    public class Dest_host
    {
        [XmlAttribute(AttributeName = "value")]
        public string Value { get; set; }
    }

    [XmlRoot(ElementName = "dest_port")]
    public class Dest_port
    {
        [XmlAttribute(AttributeName = "value")]
        public string Value { get; set; }
    }

    [XmlRoot(ElementName = "value")]
    public class Value
    {
        [XmlAttribute(AttributeName = "name")]
        public string Name { get; set; }
        [XmlAttribute(AttributeName = "type")]
        public string Type { get; set; }
        [XmlAttribute(AttributeName = "default")]
        public string Default { get; set; }
    }

    [XmlRoot(ElementName = "message")]
    public class Message
    {
        [XmlElement(ElementName = "value")]
        public List<Value> Value { get; set; }
    }

    [XmlRoot(ElementName = "config")]
    public class Config
    {
        [XmlElement(ElementName = "table_host")]
        public Table_host Table_host { get; set; }
        [XmlElement(ElementName = "comm_mode")]
        public Comm_mode Comm_mode { get; set; }
        [XmlElement(ElementName = "dest_host")]
        public Dest_host Dest_host { get; set; }
        [XmlElement(ElementName = "dest_port")]
        public Dest_port Dest_port { get; set; }
        [XmlElement(ElementName = "message")]
        public Message Message { get; set; }
    }

}